version: "3.7"
services:

    apromore:
        build: ./apromore
        image: apromore
        volumes:
            - "./apromore/Editor-Repository:/opt/apromore/Editor-Repository"
            - "./apromore/Event-Logs-Repository:/opt/apromore/Event-Logs-Repository"
            - "./apromore/Filestore-Repository:/opt/apromore/Filestore-Repository"
            - "./apromore/Lucene-Repository:/opt/apromore/Lucene-Repository"
        depends_on:
            - mysql
            - kafka
        ports:
            - "9000:9000"

    mysql:
        image: mysql:5.6.42
        # override the mysql config and set max_allowed_packet to 2G
        # or else dump sql could not restore DB successfully
        command: --max_allowed_packet=2G
        environment:
            MYSQL_ROOT_PASSWORD: MAcri
            MYSQL_DATABASE: apromore
            MYSQL_USER: apromore
            MYSQL_PASSWORD: MAcri
        volumes:
            # - "./mysql_init:/docker-entrypoint-initdb.d" # Place init .sql file(s) here
            - "./apromore/mysql-data:/var/lib/mysql"
        expose:
            - "3306"


    # Following services are required for the Predictive Training plugin

    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        expose:
            - "2181"
    kafka:
        image: wurstmeister/kafka:2.12-2.1.0
        depends_on:
            - zookeeper
        expose:
            - "9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "events:1:1,prefixes:1:1,predictions:1:1,control:1:1"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"

    nirdizati_collator:
        build: ./nirdizati_collator
        image: nirdizati_collator
        depends_on:
            - kafka

    nirdizati_predict:
        build: ./nirdizati_predict
        image: nirdizati_predict
        depends_on:
            - kafka

            