# This file is part of "Apromore Core".
#
# Copyright (C) 2018 - 2020, Apromore Pty Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Lesser Public License for more details.
#
# You should have received a copy of the GNU General Lesser Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/lgpl-3.0.html>.

version: "3.7"
services:
    apromore:
        image: apromore/community:7.15
        container_name: apromore
        environment:
            JAVA_OPTS: "-server -Xmx8g -Xmn1g"
        volumes:
            - "./site.properties:/opt/apromore/virgo-tomcat-server-3.6.4.RELEASE/repository/usr/site.properties"
            - "./Event-Logs-Repository:/opt/Event-Logs-Repository"
        ports:
            - "80:9000"
        depends_on:
            - apromoresql
    apromoresql:
        image: mysql:5.7
        container_name: apromoresql
        command: --max_allowed_packet=2G
        environment:
            MYSQL_DATABASE: apromore
            MYSQL_ROOT_PASSWORD: MAcri
            MYSQL_USER: apromore
            MYSQL_PASSWORD: MAcri
        volumes:
            - "./mysql-data:/var/lib/mysql"
        expose:
            - "3306"          