TYPE=VIEW
query=select `apromore`.`process`.`id` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from `apromore`.`process` union select `apromore`.`process`.`name` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from `apromore`.`process` union select `apromore`.`process`.`domain` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from `apromore`.`process` union select `apromore`.`native_type`.`nat_type` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from (`apromore`.`process` join `apromore`.`native_type` on((`apromore`.`process`.`nativeTypeId` = `apromore`.`native_type`.`id`))) union select `apromore`.`user`.`first_name` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from (`apromore`.`process` join `apromore`.`user` on((`apromore`.`process`.`owner` = `apromore`.`user`.`username`))) union select `apromore`.`user`.`last_name` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from (`apromore`.`process` join `apromore`.`user` on((`apromore`.`process`.`owner` = `apromore`.`user`.`username`))) union select `apromore`.`process_branch`.`branch_name` AS `value`,\'process\' AS `type`,`apromore`.`process_branch`.`processId` AS `processId`,NULL AS `logId`,NULL AS `folderId` from `apromore`.`process_branch` union select `apromore`.`log`.`id` AS `value`,\'log\' AS `type`,NULL AS `processId`,`apromore`.`log`.`id` AS `logId`,NULL AS `folderId` from `apromore`.`log` union select `apromore`.`log`.`name` AS `value`,\'log\' AS `type`,NULL AS `processId`,`apromore`.`log`.`id` AS `logId`,NULL AS `folderId` from `apromore`.`log` union select `apromore`.`log`.`domain` AS `value`,\'log\' AS `type`,NULL AS `processId`,`apromore`.`log`.`id` AS `logId`,NULL AS `folderId` from `apromore`.`log` union select `apromore`.`folder`.`folder_name` AS `value`,\'folder\' AS `type`,NULL AS `processId`,NULL AS `logId`,`apromore`.`folder`.`id` AS `folderId` from `apromore`.`folder`
md5=1e7d74a1d0ff219bb02d056ca95b2c4c
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2020-05-15 03:18:34
create-version=1
source=select process.id\n    AS value, \'process\' AS type, process.id AS processId, NULL AS logId, NULL AS folderId\n    from process union\n  select process.name\n    AS value, \'process\' AS type, process.id AS processId, NULL AS logId, NULL AS folderId\n    from process union\n  select process.domain\n    AS value, \'process\' AS type, process.id AS processId, NULL AS logId, NULL AS folderId\n    from process union\n  select native_type.nat_type\n    AS value, \'process\' AS type, process.id AS processId, NULL AS logId, NULL AS folderId\n    from process join native_type ON (process.nativeTypeId = native_type.id) union\n  select `user`.first_name\n    AS value, \'process\' AS type, process.id AS processId, NULL AS logId, NULL AS folderId\n    from process join `user` ON (process.owner = `user`.username) union\n  select `user`.last_name\n    AS value, \'process\' AS type, process.id AS processId, NULL AS logId, NULL AS folderId\n    from process join `user` ON (process.owner = `user`.username) union\n  select process_branch.branch_name\n    AS value, \'process\' AS type, process_branch.processId AS processId, NULL AS logId, NULL AS folderId\n    from process_branch union\n  select `log`.id\n    AS value, \'log\' AS type, NULL AS processId, `log`.id AS logId, NULL AS folderId\n    from `log` union\n  select `log`.name\n    AS value, \'log\' AS type, NULL AS processId, `log`.id AS logId, NULL AS folderId\n    from `log` union\n  select `log`.domain\n    AS value, \'log\' AS type, NULL AS processId, `log`.id AS logId, NULL AS folderId\n    from `log` union\n  select folder.folder_name\n    AS value, \'folder\' AS type, NULL AS processId, NULL AS logId, folder.id AS folderId\n    from folder
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `apromore`.`process`.`id` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from `apromore`.`process` union select `apromore`.`process`.`name` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from `apromore`.`process` union select `apromore`.`process`.`domain` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from `apromore`.`process` union select `apromore`.`native_type`.`nat_type` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from (`apromore`.`process` join `apromore`.`native_type` on((`apromore`.`process`.`nativeTypeId` = `apromore`.`native_type`.`id`))) union select `apromore`.`user`.`first_name` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from (`apromore`.`process` join `apromore`.`user` on((`apromore`.`process`.`owner` = `apromore`.`user`.`username`))) union select `apromore`.`user`.`last_name` AS `value`,\'process\' AS `type`,`apromore`.`process`.`id` AS `processId`,NULL AS `logId`,NULL AS `folderId` from (`apromore`.`process` join `apromore`.`user` on((`apromore`.`process`.`owner` = `apromore`.`user`.`username`))) union select `apromore`.`process_branch`.`branch_name` AS `value`,\'process\' AS `type`,`apromore`.`process_branch`.`processId` AS `processId`,NULL AS `logId`,NULL AS `folderId` from `apromore`.`process_branch` union select `apromore`.`log`.`id` AS `value`,\'log\' AS `type`,NULL AS `processId`,`apromore`.`log`.`id` AS `logId`,NULL AS `folderId` from `apromore`.`log` union select `apromore`.`log`.`name` AS `value`,\'log\' AS `type`,NULL AS `processId`,`apromore`.`log`.`id` AS `logId`,NULL AS `folderId` from `apromore`.`log` union select `apromore`.`log`.`domain` AS `value`,\'log\' AS `type`,NULL AS `processId`,`apromore`.`log`.`id` AS `logId`,NULL AS `folderId` from `apromore`.`log` union select `apromore`.`folder`.`folder_name` AS `value`,\'folder\' AS `type`,NULL AS `processId`,NULL AS `logId`,`apromore`.`folder`.`id` AS `folderId` from `apromore`.`folder`
